config/routes.rb
Rails.application.routes.draw do
  resources :questionaires
  resources :questions
  resources :users
  resources :choices

end

app/models/questionaire.rb
class Questionaire < ActiveRecord::Base
  has_one :question
  belongs_to :user
  validates :title, presence: true
  validates :user_id, presence: true
end

app/controllers/questionaires_controller.rb
class QuestionairesController < ApplicationController
  before_action :set_questionaire, only: [:show, :edit, :update, :destroy]

  # GET /questionaires
  # GET /questionaires.json
  def index
    @questionaires = Questionaire.all
  end

  # GET /questionaires/1
  # GET /questionaires/1.json
  def show
  end

  # GET /questionaires/new
  def new
    @questionaire = Questionaire.new
  end

  # GET /questionaires/1/edit
  def edit
  end

  # POST /questionaires
  # POST /questionaires.json
  def create
    @questionaire = Questionaire.new(questionaire_params)

    respond_to do |format|
      if @questionaire.save
        format.html { redirect_to @questionaire, notice: 'Questionaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionaire }
      else
        format.html { render :new }
        format.json { render json: @questionaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionaires/1
  # PATCH/PUT /questionaires/1.json
  def update
    respond_to do |format|
      if @questionaire.update(questionaire_params)
        format.html { redirect_to @questionaire, notice: 'Questionaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionaire }
      else
        format.html { render :edit }
        format.json { render json: @questionaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionaires/1
  # DELETE /questionaires/1.json
  def destroy
    @questionaire.destroy
    respond_to do |format|
      format.html { redirect_to questionaires_url, notice: 'Questionaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionaire
      @questionaire = Questionaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionaire_params
      params.require(:questionaire).permit(:user_id, :title)
    end
end

app/helpers/questionaires_helper.rb
module QuestionairesHelper
end

app/views/questionaires/_form.html.erb
<%= form_for(@questionaire) do |f| %>
  <% if @questionaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionaire.errors.count, "error") %> prohibited this questionaire from being saved:</h2>

      <ul>
      <% @questionaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionaires/edit.html.erb
<h1>Editing Questionaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionaire %> |
<%= link_to 'Back', questionaires_path %>

app/views/questionaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questionaires</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionaires.each do |questionaire| %>
      <tr>
        <td><%= questionaire.user_id %></td>
        <td><%= questionaire.title %></td>
        <td><%= link_to 'Show', questionaire %></td>
        <td><%= link_to 'Edit', edit_questionaire_path(questionaire) %></td>
        <td><%= link_to 'Destroy', questionaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionaire', new_questionaire_path %>

app/views/questionaires/new.html.erb
<h1>New Questionaire</h1>

<%= render 'form' %>

<%= link_to 'Back', questionaires_path %>

app/views/questionaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @questionaire.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @questionaire.title %>
</p>

<%= link_to 'Edit', edit_questionaire_path(@questionaire) %> |
<%= link_to 'Back', questionaires_path %>